# Generated by Django 2.2.1 on 2019-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMdiagnose', '0006_xue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.CharField(blank=True, default='nothing', max_length=2000, null=True)),
                ('symptom', models.CharField(blank=True, default='nothing', max_length=2000, null=True)),
                ('title', models.CharField(blank=True, default='nothing', max_length=2000, null=True)),
                ('marks', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('reference', models.CharField(blank=True, default='nothing', max_length=2000, null=True)),
            ],
        ),
    ]
